# Site settings
title: "prettypositron"
bye_message: "528"
baseurl: "/528/"
url: "https://prettypositron.github.io/"
disqus:

# Header settings
nick: "prettypositron"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "prettypositron"
blog:
    server: "wordpress.com"
    nick: "prettypositron"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
#markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
permalink: /:categories/:title/
